### PR TITLE
QGIS 3

### PR DESCRIPTION
**Pull request by terry-longmacch**
Making some very preliminary updates towards QGIS 3 (probably naively!).

Hit a wall with py2exe (and the alternative cx_Freeze).  There is a new fork of py2exe that claims to have some compatibility with Python 3.7, but haven't been able to get it working, as yet (getting stuck on isSystemDLL).  Have quite a bit of experience with other languages, but not much with Python, so struggling to get my head around the flow of setup.py.

Happy to continue on, if someone can help point me in the right direction.

Cheers,
Terry

### CODE REVIEW

**Comment by NathanW2** [comment]
Wow impressive work. I can review later this week. Thanks.

Yeah we will drop py2exe and use something else I think. I have a early
branch that I can bring back alive

**Comment by terry-longmacch** [comment]
Thanks Nathan - particularly for all of your work on this great project!

I've had a few people warn me about the joys of upgrading Python projects from 2 to 3!!

**Comment by NathanW2** [comment]
Haha yes it is not as fast as I would like and the lack of unit tests don't
help here. Things I would fix if I had a time machine.

**Comment by NathanW2** [comment]
@terry-longmacch I'm going to start on a review of this starting Monday arvo hopefully.  Will be in touch.  Thanks for the start.

**Comment by NathanW2** [comment]
I have merged this now @terry-longmacch.  We will work off master for the Roam 3 update as there is a branch for 2.7.2 with fixes for that.

**Comment by terry-longmacch** [comment]
@NathanW2, just tried a commit to main branch but looks like it is still protected?  Could you please check for me?  Thanks.

**Comment by NathanW2** [comment]
@terry-longmacch master is protected from a force push to avoid nuking other changes you will need to do 

```
git pull
```
before your push

**Comment by terry-longmacch** [comment]
Sorry @NathanW2, still finding my way here.  Was using GitHub Desktop, but please see below.

```
C:\Development\Roam>git pull
Already up to date.

C:\Development\Roam>git push
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 460 bytes | 92.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/roam-qgis/Roam.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/roam-qgis/Roam.git'

```

**Comment by NathanW2** [comment]
Yeah all good.  Ok I see, Fixed now.  I missed those settings.

**Comment by terry-longmacch** [comment]
No problem, all good now.  What's the best way for me to ask you about
particular sections of code?

Regards,

Terry McDonell
Principal Consultant
*Long Macch IT Solutions*

p: 0458 238 915
w: www.longmacch.com.au

**Comment by NathanW2** [comment]
Feel free to call me if you need, or open a ticket for it and we chat on
there.

**Pull request merged**
